### ISSUE TITLE
Замена в 113 строке

### ISSUE THREAD

**Issue by dagababaev** [Ipatov/SendMailSmtpClass#3]
Предлагаю заменить строку 113 с:
    fputs($socket, "MAIL FROM: <".$this->smtp_username.">\r\n");
на:
    fputs($socket, "MAIL FROM: <".$smtp_from[1].">\r\n");
    
Причина:
$this->smtp_username содержит в себе имя с которым мы авторизуемся на сервере, если же на сервере (например Synology MailPlus) происходит авторизация не по почтовому адресу, а по логину, то в первом случае в FROM будет несуществующий адрес и письмо гарантированно упадет в СПАМ.
Во втором случае мы берем адрес отправителя из массива (второй элемент), а там как раз всегда адрес эл. почты

**Comment by Ipatov** [comment]
хорошая идея, добавил в код
